import 'recipe.dart';

/// Small static catalog of simple, realistic recipes shown as "Suggested"
/// picks whenever a user hasn't created any recipes of their own yet, so the
/// Meal Planner and recipe picker never demo completely empty.
///
/// Every entry carries the `'suggested'` tag (see `Recipe.isSuggested`) so
/// the UI can badge it distinctly from the user's own recipes, and so the
/// picker knows to persist a real copy (via `createRecipe`) before it can be
/// assigned to a meal slot.
final List<Recipe> curatedRecipes = [
  const Recipe(
    id: 'curated-overnight-oats',
    title: 'Overnight Oats with Berries',
    prepMinutes: 5,
    servings: 1,
    category: RecipeCategory.healthy,
    calories: 320,
    proteinGrams: 12,
    tags: ['suggested', 'breakfast'],
    ingredients: [
      Ingredient(name: 'Rolled oats', quantity: 0.5, unit: 'cup'),
      Ingredient(name: 'Milk', quantity: 1, unit: 'cup'),
      Ingredient(name: 'Mixed berries', quantity: 0.5, unit: 'cup'),
      Ingredient(name: 'Chia seeds', quantity: 1, unit: 'tbsp'),
      Ingredient(name: 'Honey', quantity: 1, unit: 'tbsp'),
    ],
    instructions: [
      'Stir the oats, milk, and chia seeds together in a jar.',
      'Cover and refrigerate overnight (at least 6 hours).',
      'Top with berries and a drizzle of honey before serving.',
    ],
  ),
  const Recipe(
    id: 'curated-veggie-scramble',
    title: 'Veggie Egg Scramble',
    prepMinutes: 10,
    servings: 1,
    category: RecipeCategory.quick,
    calories: 280,
    proteinGrams: 18,
    tags: ['suggested', 'breakfast'],
    ingredients: [
      Ingredient(name: 'Eggs', quantity: 2, unit: 'pcs'),
      Ingredient(name: 'Bell pepper', quantity: 0.5, unit: 'pcs'),
      Ingredient(name: 'Spinach', quantity: 1, unit: 'cup'),
      Ingredient(name: 'Cherry tomatoes', quantity: 5, unit: 'pcs'),
      Ingredient(name: 'Olive oil', quantity: 1, unit: 'tsp'),
    ],
    instructions: [
      'Whisk the eggs in a bowl and set aside.',
      'Sauté the pepper and tomatoes in olive oil for 2 minutes.',
      'Add spinach and cook until wilted, then pour in the eggs.',
      'Scramble gently over medium heat until just set.',
    ],
  ),
  const Recipe(
    id: 'curated-grilled-chicken-salad',
    title: 'Grilled Chicken Salad',
    prepMinutes: 20,
    servings: 2,
    category: RecipeCategory.healthy,
    calories: 450,
    proteinGrams: 35,
    tags: ['suggested', 'lunch'],
    ingredients: [
      Ingredient(name: 'Chicken breast', quantity: 2, unit: 'pcs'),
      Ingredient(name: 'Mixed greens', quantity: 4, unit: 'cup'),
      Ingredient(name: 'Avocado', quantity: 1, unit: 'pcs'),
      Ingredient(name: 'Cherry tomatoes', quantity: 10, unit: 'pcs'),
      Ingredient(name: 'Olive oil', quantity: 2, unit: 'tbsp'),
    ],
    instructions: [
      'Season the chicken breasts and grill for 6-7 minutes per side.',
      'Let the chicken rest, then slice.',
      'Toss the greens, tomatoes, and avocado with olive oil.',
      'Top the salad with sliced chicken and serve.',
    ],
  ),
  const Recipe(
    id: 'curated-turkey-wrap',
    title: 'Turkey & Avocado Wrap',
    prepMinutes: 10,
    servings: 1,
    category: RecipeCategory.quick,
    calories: 390,
    proteinGrams: 24,
    tags: ['suggested', 'lunch'],
    ingredients: [
      Ingredient(name: 'Whole wheat tortilla', quantity: 1, unit: 'pcs'),
      Ingredient(name: 'Sliced turkey', quantity: 4, unit: 'oz'),
      Ingredient(name: 'Avocado', quantity: 0.5, unit: 'pcs'),
      Ingredient(name: 'Lettuce', quantity: 1, unit: 'cup'),
    ],
    instructions: [
      'Lay the tortilla flat and spread mashed avocado over it.',
      'Layer the turkey and lettuce on top.',
      'Roll tightly and slice in half to serve.',
    ],
  ),
  const Recipe(
    id: 'curated-salmon-veggies',
    title: 'One-Pan Salmon & Veggies',
    prepMinutes: 25,
    servings: 2,
    category: RecipeCategory.healthy,
    calories: 520,
    proteinGrams: 38,
    tags: ['suggested', 'dinner'],
    ingredients: [
      Ingredient(name: 'Salmon fillet', quantity: 2, unit: 'pcs'),
      Ingredient(name: 'Broccoli', quantity: 2, unit: 'cup'),
      Ingredient(name: 'Baby potatoes', quantity: 10, unit: 'pcs'),
      Ingredient(name: 'Olive oil', quantity: 2, unit: 'tbsp'),
      Ingredient(name: 'Lemon', quantity: 1, unit: 'pcs'),
    ],
    instructions: [
      'Preheat the oven to 400°F (200°C).',
      'Toss the potatoes and broccoli in olive oil and roast for 15 minutes.',
      'Add the salmon to the pan and roast for another 10-12 minutes.',
      'Squeeze fresh lemon over everything before serving.',
    ],
  ),
  const Recipe(
    id: 'curated-bean-chili',
    title: 'Budget Bean Chili',
    prepMinutes: 30,
    servings: 4,
    category: RecipeCategory.budget,
    calories: 340,
    proteinGrams: 16,
    tags: ['suggested', 'dinner'],
    ingredients: [
      Ingredient(name: 'Canned kidney beans', quantity: 2, unit: 'cans'),
      Ingredient(name: 'Canned tomatoes', quantity: 1, unit: 'can'),
      Ingredient(name: 'Onion', quantity: 1, unit: 'pcs'),
      Ingredient(name: 'Garlic', quantity: 2, unit: 'cloves'),
      Ingredient(name: 'Chili powder', quantity: 1, unit: 'tbsp'),
    ],
    instructions: [
      'Sauté the diced onion and garlic until soft.',
      'Stir in the chili powder and cook for 1 minute.',
      'Add the beans and tomatoes, then simmer for 20 minutes.',
      'Season to taste and serve warm.',
    ],
  ),
  const Recipe(
    id: 'curated-veggie-stir-fry',
    title: 'Veggie Stir Fry',
    prepMinutes: 20,
    servings: 3,
    category: RecipeCategory.budget,
    calories: 310,
    proteinGrams: 10,
    tags: ['suggested', 'dinner'],
    ingredients: [
      Ingredient(name: 'Mixed stir-fry vegetables', quantity: 4, unit: 'cup'),
      Ingredient(name: 'Rice', quantity: 2, unit: 'cup'),
      Ingredient(name: 'Soy sauce', quantity: 3, unit: 'tbsp'),
      Ingredient(name: 'Garlic', quantity: 2, unit: 'cloves'),
      Ingredient(name: 'Sesame oil', quantity: 1, unit: 'tbsp'),
    ],
    instructions: [
      'Cook the rice according to package instructions.',
      'Stir-fry the garlic in sesame oil for 30 seconds.',
      'Add the vegetables and stir-fry over high heat for 5-6 minutes.',
      'Stir in the soy sauce and serve over rice.',
    ],
  ),
  const Recipe(
    id: 'curated-greek-yogurt-parfait',
    title: 'Greek Yogurt Parfait',
    prepMinutes: 5,
    servings: 1,
    category: RecipeCategory.quick,
    calories: 220,
    proteinGrams: 20,
    tags: ['suggested', 'snack'],
    ingredients: [
      Ingredient(name: 'Greek yogurt', quantity: 1, unit: 'cup'),
      Ingredient(name: 'Granola', quantity: 0.25, unit: 'cup'),
      Ingredient(name: 'Mixed berries', quantity: 0.5, unit: 'cup'),
    ],
    instructions: [
      'Spoon half the yogurt into a glass.',
      'Layer with half the berries and granola.',
      'Repeat the layers and serve immediately.',
    ],
  ),
];
